In [2]:
import torch

torch.load('../trained_backbones/csi_cifar10_unlabeled.pth')

OrderedDict([('linear.weight',
              tensor([[-0.2520, -0.1230,  0.4879,  ..., -0.4460, -0.3157,  0.4403],
                      [ 0.2329,  0.4094, -0.0292,  ...,  0.3173,  0.1356, -0.0086],
                      [ 0.4210, -0.3205, -0.3362,  ..., -0.4275,  0.1570, -0.2277],
                      ...,
                      [ 0.0318,  0.1097,  0.2258,  ...,  0.1534,  0.0259, -0.0530],
                      [-0.0033, -0.7719,  0.1580,  ...,  0.9540, -0.1931,  0.2797],
                      [-0.1056,  0.6156, -0.0898,  ..., -0.4709,  0.1202, -0.2281]],
                     device='cuda:0')),
             ('linear.bias',
              tensor([ 0.3999, -0.1733,  0.2531,  0.1852, -0.1305,  0.0471, -0.1926, -0.3295,
                      -0.0944, -0.3418], device='cuda:0')),
             ('simclr_layer.0.weight',
              tensor([[ 0.1101, -0.2912, -0.0814,  ..., -0.0865, -0.1246, -0.0485],
                      [-0.1628,  0.1468,  0.0649,  ..., -0.0386,  0.1345, -0.0615],
       